### ISSUE TITLE
Further comments from Ilari

### ISSUE THREAD

**Issue by gselander** [cose-wg/CBOR-certificates#102]
https://mailarchive.ietf.org/arch/msg/cose/1z42o2SlausqLDoyr_WTUNf39HQ/

I have written a test CBOR X509 codec. From its issue notes, I found a
related issue note:

 "GeneralName can start with uint, so it is pretty nasty to determine
 if any uint in maximum position is in fact a maximum or start of
 next name. This probably will not work at all if GeneralName ever
 gains a type that can take uint as argument. And since minimum has
 a default, it is in fact optional, so the only required field is
 the GeneralName one."
 
However, the issue resolution note is busted (broken CDDL), and looking
at the code, the minimum/maximum handling is FUBAR.

In light of Corey's above mail, I just ripped out the minimum/maximum
handling, making those generate extension unencodeable if present.

Now each X.509 GeneralSubtree is encoded as CBOR GeneralName.

Some other notes I found:

 Certificate policies extension:

  The qualifier value field is of type dependent of qualifier id.
  Different qualfiers seem to put different things there. CPS seems
  to be IA5String, and unotice seems to be sequence{text}. If some cert
  has something else, who knows what the value is. The value field in
  CBOR is text, so sticking raw ASN.1 blobs is not possible.

  => Only qualifiers id-qt-cps and id-qt-unotice are supported.

* Key Usage extension:

  The present encoding seems to be ambiguous. For example, both 06 C0
  (committing signature certificate) and 01 06 (CA certificate) seem
  to encode as integer 3. With 1 prepended, those encode as integer 7
  and integer 131 respecively.

  => Prepend 1 bit to key usage before encoding.

* Name Constraints extension:

  Both permitted and excluded fields are optional, but the spec is not
  clear how missing field is encoded. The cbor-cert spec allows for
  empty array, while PKIX does not allow empty field. However, for
  implementations, it would be easier to encode absent field as
  null.

  => Encode missing permitted/excluded as null.

* Subject Directory Attributes extension:

  The ASN.1 is effectively list of tuples of OID and set.
  The CBOR is tuple of OID and set. There is no obvious way to map
  between the two. Furthermore, the present construction produces
  two values, which is not legal for extension, which can only
  produce one.

  => Use SubjectDirectoryAttributes = [+Attributes]

* Attribute table:

  Presently jurisdictionOfIncorporationCountryName and domainComponent
  both have id 21.
  
  => Encode domainComponent as 22.

* AS numbers extension:

  Is there a reason the numbers can not backjump?
  
  => Encode backjumps by overflowing 32-bit ASN.

* "AS Resources v2 (id-pe-ipAddrBlocks-v2)":

  I presume the OID should be id-pe-autonomousSysIds-v2.
  
* Section about "IP Resources" talks about "previous ASid".

  This looks odd...

* IPv6 address encoding can overflow:

  In encoding IPv6 addresses, the address differences can overflow
  uint. However, I do not expect this happening outside pathological
  cases, especially as CBOR ints go to full size of IPv6 subnetwork
  identifier.

* The encodings of Brainpool curves:

  The payload seems to be 20 octets, but the topmost TLV has length of
  19.

  => Fix topmost TLV length to 20 (0x14).

 * The encodings of ANSSI curve:

  The payload seems to be 21 octets, but the topmost TLV has length of
  19.

  => Fix topmost TLV length to 21 (0x15).

* Authority Key Identifier Extension:

  In pile of CA certs I have laying around, about 1/10 lack keyid in
  AKI.

  => Encode absent keyid as null.

Throwing the pile of CA certs I have at the implementation:

* 24 certificates have fatal errors that prevent compression:
  - 15 have bad notBefore
  - 3 have EKU explicitly not critical
  - 2 are X509v1 certificates
  - 2 have disagreeing signature algorithms
  - 1 has negative serial number
  - 1 has bad notAfter
* 15 certs hit error encoding CRL Distribution Point:
  ("Entry is not a pure DISTRIBUTION_POINT")
* 405 certs hit error encoding Certificate Policies:
  - 326 "Unsupported VisibleString notice"
  - 42 "Unsupported BMPString notice"
  - 29 "Unsupported notice reference"
  - 8 "FFCS VisibleString"
- 5 certs hit error encoding Authority Key Identifier:
  ("Invalid serial in AKI").
- 236 certs have Authority Key Identifier without keyid.

**Comment by highlunder** [comment]
Regarding subitem 4, Name Constraints extension::

Updated spec to allow null:

NameConstraints = [ 
     permittedSubtrees: GeneralSubtree / null,
     excludedSubtrees: GeneralSubtree / null,
]

**Comment by highlunder** [comment]
Regarding sub-item 5, Subject Directory Attributes extension:

Updated spec, following suggestion to wrap Attributes as [+Attributes]

**Comment by highlunder** [comment]
Regarding sub-item 6, Attribute table:

domainComponent updated / fixed to 22

**Comment by highlunder** [comment]
Regarding sub-iten 8, AS Resources v2:

Fixed to autonomousSysIds-v2

**Comment by highlunder** [comment]
Regarding sub-item 9, IP Resources:

Fixed typos/copy-paste errors to "Address"

**Comment by highlunder** [comment]
Regarding sub-item 10, IPv6 address encoding can overflow:

Added a line to acknowledge the known limitation

**Comment by highlunder** [comment]
Regarding sub-item 11 & 12: encodings of Brainpool curves + ANSSI / FRP256v1 curve:

Corrected the DER encoded lengths

**Comment by highlunder** [comment]
About sub-item 7: AS numbers extension: "Is there a reason the numbers can not backjump?"

I haven't found one besides slightly more complex parsing. I suggest changing from uint to to int, here:

https://github.com/cose-wg/CBOR-certificates/pull/106

**Comment by highlunder** [comment]
Ok, about sub-item 7, the relevant draft actually requires the ASIds to be sorted; "The AS identifiers in the asIdsOrRanges element MUST be sorted by increasing numeric value.", [3.2.3.4](https://www.rfc-editor.org/rfc/rfc3779#section-3.2.3.4). Element asIdsOrRanges

Given this, let's not allow certificates with malformed ASId-specifications!

**Comment by highlunder** [comment]
About sub-item 2: Certificate policies extension: 

After asking the community whether more extensive support for additional qualifiers is needed, we are ok with the existing limitations. They are in line with the recommendations in rfc5280 [4.2.1.4](https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.4).  Certificate Policies

**Comment by highlunder** [comment]
About sub-item 14: Malformed CA certs, "Throwing the pile of CA certs I have at the implementation:..."

After further discussions, internally and COSE general, on the tolerance for non-standard behaviours, we conclude to ignore the issue of existing malformed CA certificates.

**Comment by highlunder** [comment]
About sub-item 1: GeneralName can start with uint, and the resulting problems:

Fixed in 6d4ca3c

Name Constraints (nameConstraints). If the name constraints only contains general names registered in {{GN}} the extension value can be CBOR encoded. Note that {{RFC5280}} requires that minimum MUST be zero, and maximum MUST be absent.

GeneralSubtree = [ GeneralName ]

**Comment by highlunder** [comment]
Status check: the only thing missing is a minor code update: subproblem 3

**Comment by highlunder** [comment]
#162 contains updated code for the example implementation, among other things addressing the bug that formed subproblem 3 mentioned above. And since this was the remaining open subproblem, this issue is now (finally) resolved!
