### ISSUE TITLE
Remove myself from acknowledgements

### ISSUE THREAD

**Issue by letmaik** [cose-wg/CBOR-certificates#103]
I noticed that a misspelling of my name appears in https://datatracker.ietf.org/doc/html/draft-ietf-cose-cbor-encoded-cert-04 under acknowledgements. Can you please remove me? The only commit to this repo that I made was to fix a URL in the README. I don't think this should be the bar to be included in the acknowledgements.

**Comment by highlunder** [comment]
We're sorry for the typo! Name removed, but we're of course happy to add it back, with the proper spelling, if you find other draft issues to contribute to.
