### ISSUE TITLE
encoding of Weierstrass EC public key in the native C509 certificate

### ISSUE THREAD

**Issue by highlunder** [cose-wg/CBOR-certificates#110]
It is not clear whether the EC Point (public key) is uncompressed encoded (starting with 0x04) or compressed (starting with 0x02 or 0x03) is used in the native C509 certificate.

If uncompressed encoded, then the following text needs to be adapted:

'For elliptic curve public keys in Weierstrass form (id-ecPublicKey), *uncompressed keys are point compressed* as defined in Section 2.3.3 of [[SECG](https://www.ietf.org/archive/id/draft-ietf-cose-cbor-encoded-cert-05.html#SECG)]'.

A suggestion is
'For elliptic curve public keys in Weierstrass form (id-ecPublicKey), *public keys are uncompressed encoded EC points* as defined in Section 2.3.3 of [[SECG](https://www.ietf.org/archive/id/draft-ietf-cose-cbor-encoded-cert-05.html#SECG)]'.

**Comment by xipki** [comment]
Compressed point encoding may be problematic.
1. Compressed point is deprecated in TLS 1.2 and 1.3,
2. Not supported in mbedTLS, which is widely used in lots of embedded devices.
