### ISSUE TITLE
Why not uncompressed-encode the Weierstrass EC public key in the native C509 certificate?

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#115]
I my view, the only advantage of compressed point encoding is the reduce size (e.g., 32 bytes compared to uncompressed for P-256 curve).

This, however, is problematic, since it is not so widely supported as the uncompressed version, e.g. unsupported in mbedTLS (https://github.com/Mbed-TLS/mbedtls/issues/861).

Please also note the compressed point is deprecated in TLS 1.2 and 1.3 (https://datatracker.ietf.org/doc/html/draft-ietf-tls-rfc4492bis-16#section-5.1.2).

**Comment by highlunder** [comment]
We believe that point compression will be relevant in the future, even if the current support is less than desired. To address this, we are currently discussing how we could also support uncompressed versions of the keys.

**Comment by emanjon** [comment]
I made a PR supporting uncompressed. #117

**Comment by emanjon** [comment]
My reading of RFC 8422 and RFC 8446 are that they are for the ECDHE key shares. TLS typically does not specify anything about X.509 as that is out of scope of TLS.

Calculating the uncompressed y coordinate is not very hard as explained in Section 3.2 of https://datatracker.ietf.org/doc/html/draft-mattsson-tls-compact-ecc-04

`we can calculate y as the square root w = (x^3 + a ⋅ x + b)^((p + 1)/4) (mod p)`

This is very simple math, nothing ECC specific and the implementation does not need any specific security considerations as it operates on public data. But maybe it is problematic to implement on more contrained devices.

**Comment by highlunder** [comment]
With the latest update from John, both compressed and uncompressed encodings of Weierstrass EC public keys are supported. We think this is the best way forward.
