### ISSUE TITLE
Add support for challengePassword attribute

### ISSUE THREAD

**Issue by gselander** [cose-wg/CBOR-certificates#124]
Section 4 states that

> CSR attributes other than extensionRequest are not supported.

but the challengePassword attribute is used in [RFC 9148](https://www.rfc-editor.org/rfc/rfc9148) and [est-oscore](https://datatracker.ietf.org/doc/draft-ietf-ace-coap-est-oscore/) and should also be supported.

In PKCS#9 ([RFC 2985](https://www.ietf.org/rfc/rfc2985)) and PKCS#10 ([RFC 2986](https://www.ietf.org/rfc/rfc2986)), challengePassword is encoded as a text string and the example given is for revocation, which probably is not relevant. 

In SCEP ([RFC 8994](https://www.ietf.org/rfc/rfc8994)), challengePassword is intended to be a shared secret, and it is RECOMMENDED to be a one-time authenticator.

In the later references mentioned above challengePassword is used for associating the certificate request to the authenticated session and the assumed encoding is byte string.

**Comment by gselander** [comment]
Should we add general attributes, or just challengePassword as an additional field?

OLD
TBSCertificateRequest = (
   c509CertificateRequestType: int,
   subject: Name,
   subjectPublicKeyAlgorithm: AlgorithmIdentifier,
   subjectPublicKey: any,
   extensionsRequest : Extensions,
   subjectProofOfPossessionAlgorithm: AlgorithmIdentifier,
)


NEW
TBSCertificateRequest = (
   c509CertificateRequestType: int,
   subject: Name,
   subjectPublicKeyAlgorithm: AlgorithmIdentifier,
   subjectPublicKey: any,
   _**challengePassword: bstr / null,**_
   extensionsRequest : Extensions,
   subjectProofOfPossessionAlgorithm: AlgorithmIdentifier,
)

(or is it _**nil**_?)

**Comment by highlunder** [comment]
We propose to add the challenge password as an Extension, part of the extensionsRequest field. This would save the otherwise additional null-byte needed to always have the option present at the top level.

**Comment by highlunder** [comment]
Pushed!

**Comment by xipki** [comment]
> Should we add general attributes, or just challengePassword as an additional field?
> 
> OLD TBSCertificateRequest = ( c509CertificateRequestType: int, subject: Name, subjectPublicKeyAlgorithm: AlgorithmIdentifier, subjectPublicKey: any, extensionsRequest : Extensions, subjectProofOfPossessionAlgorithm: AlgorithmIdentifier, )
> 
> NEW TBSCertificateRequest = ( c509CertificateRequestType: int, subject: Name, subjectPublicKeyAlgorithm: AlgorithmIdentifier, subjectPublicKey: any, _**challengePassword: bstr / null,**_ extensionsRequest : Extensions, subjectProofOfPossessionAlgorithm: AlgorithmIdentifier, )
> 
> (or is it _**nil**_?)

Just for clarity, adding new field `challengePassword:bstr/null`does not work here for re-encoded X.509 CSR. Since the position relationship between the attribute `challengePassword`and the attribute `extensionsRequest`is lost.
