### ISSUE TITLE
Encoding of timestamp

### ISSUE THREAD

**Issue by gselander** [cose-wg/CBOR-certificates#128]
> the timestamp is encoded as a CBOR int (milliseconds since validityNotBefore)

Is CBOR int correct? validityNotBefore is encoded as Time.

**Comment by highlunder** [comment]
Since the timestamp tag is defined as millisec in rfc6962, we keep it as millisec encoded as long/int for practical purposes.

https://datatracker.ietf.org/doc/html/rfc6962
