### ISSUE TITLE
Missing media types and content formats

### ISSUE THREAD

**Issue by gselander** [cose-wg/CBOR-certificates#136]
https://github.com/ace-wg/est-oscore/issues/34 requests definition of media types, including that of CBOR encoded CSR.

**Comment by highlunder** [comment]
+We should support cbor encoding of private keys, and define corresponding media types (see PKCS#8 for origin)

**Comment by EskoDijk** [comment]
As an equivalent of the PKCS #8 encoding of a private key, isn't that just equivalent to a COSE-key structure which is already defined for COSE?  I'm hoping we can re-use where we can.  application/cose-key is already registered.

**Comment by gselander** [comment]
I added a media type for C509RegistrationRequest.

I think @EskoDijk has a point that we should be able to use the media type application/cose-key for a COSE key instead of defining a new for transporting some encoding of PKCS#8 (which?).

Have we then resolved https://github.com/ace-wg/est-oscore/issues/34 ?

**Comment by malishav** [comment]
Another thing that is missing is the registration of CoAP Content-Format identifiers for the newly registered Media Types.

**Comment by emanjon** [comment]
Another thing that is missing is the registration of CoAP Content-Format identifiers for the newly registered Media Types.

Would we need several content formats indicating chain and bag? Or is just chain enough?

**Comment by EskoDijk** [comment]
From what I see in the registration text there's two possible CoAP content-format IDs:

* application/cose-c509
* application/cose-c509;usage=chain

Now both media types could contain either one C509Certificate, or a CBOR array of two or more C509Certificate.  (Arguably a chain of 1 is not so useful, but it's allowed, right?)

This would mean you get 2 CoAP content-formats. The single cert case and the bag case are captured by the first.

One question this brings up: if a receiver receives media type "application/cose-c509" data, and the top level structure is a CBOR array of length 2, how would it easily detect whether this is
1) a single C509Certificate, or 
2) a bag with two C509Certificates in it?

**Comment by emanjon** [comment]
>Arguably a chain of 1 is not so useful, but it's allowed, right?)
Yes

>One question this brings up: if a receiver receives media type "application/cose-c509" data, and >the top level structure is a CBOR array of length 2, how would it easily detect whether this is
>
>    a single C509Certificate, or
>    a bag with two C509Certificates in it?

You would need to look at the content. A single C509Certificate would be an array of length 11 while a bag with two C509Certificates would have length 2. To differentiate between a single C509Certificate and a bag with 11 C509Certificates you would need to look at the first element and see if it is an int or an array.

Would you need to determine that there is a single C509Certificate from the media type/content format alone without looking? We could potentially change both the media format or the encoding if needed.

`COSE_C509 = C509Certificate / [ 2* C509Certificate ]
`

**Comment by EskoDijk** [comment]
Thanks @emanjon ; I see I made a mistake here in the example (not knowing the CDDL syntax exactly ... ) 

So the example could be a single cert (array of length 11) vs a bag of certs with 11 certs in it (array of length 11). It's unclear based on length alone, but looking at the first element would resolve it (either an int - or an array of length 11 - or something else, which then renders the data invalid).

> Would you need to determine that there is a single C509Certificate from the media type/content format alone without looking?

Not sure.  For X509 certs this distinction is made, e.g. single cert in type application/pkix-cert and a bag of certs in application/pkcs7-mime. But I don't see problems in doing it in one for C509.  (Perhaps some IETFers may not like doing this trial-and-error type of content processing to detect which flavor we're dealing with.)

**Comment by emanjon** [comment]
>application/pkix-cert and a bag of certs in application/pkcs7-mime

Yes, the question is if this is just for historical reasons or if it is useful...

**Comment by emanjon** [comment]
With content formats likely to be specified that will also be part of the file format #81.

From RFC 9277:
  

>    For CBOR data items that form a
>    representation that is already described by such a Content-Format
>    Number, a tag number has proactively been allocated in Section 4.3
>    (see Appendix B for details and examples).

**Comment by highlunder** [comment]
Fixed!
