### ISSUE TITLE
Should NotAfter be made optional?

### ISSUE THREAD

**Issue by highlunder** [cose-wg/CBOR-certificates#137]
From Mike Ounsworth on the [COSE] draft-ietf-cose-cbor-encoded-cert-lists:

"The fact that notAfter is a mandatory field in X.509 is a major headache in some cases. RFC 5280 defines the special value 

   To indicate that a certificate has no well-defined expiration date,
   the notAfter SHOULD be assigned the GeneralizedTime value of
   99991231235959Z.

But in practice, this is not widely supported or even well-known enough to be universally usable.

Idea: could notAfter be made optional in C509? When transcoding to X.509 I suppose you would have to replace an absent notAfter with the GeneralizedTime value of 99991231235959Z.

The same could maybe be considered for notBefore."

**Comment by gselander** [comment]
Already included, using null!
