### ISSUE TITLE
Encoding of Name with only one attribute CommonName

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#140]
In Section 3.1: `If the text string contains only the symbols '0'–'9' or 'a'–'f', it is encoded as a CBOR byte string, prefixed with an initial byte set to '00'.`

My questions are:
1. What is about the upper-case hex letters `A-F` Shall common name with (only upper-case / mixed lower-case and upper-case)  hex letters also be encoded?
2. What if the text string have odd number of letters? If a zero is prefixed, then how to know whether it starts with `0X` or `X`?

**Comment by xipki** [comment]
That is fine. But you need to add the limitation (even number of letters) to the text.

**Comment by xipki** [comment]
I cannot re-open this issue.
@highlunder Can you re-open this issue? I will appreciate if you can let an answered issue open for comments, and let the issue creator to resolve the issue.

**Comment by gselander** [comment]
> That is fine. But you need to add the limitation (even number of letters) to the text.

This is #135.
