### ISSUE TITLE
Larger reserved type areas for private attributes and extensions

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#142]
In the industrial areas, it is not uncommon to have private subject attribute and private extension. Surely one can use the `OID` instead of `int` to identify the attribute / extension, this, however, is usually too complicated. Can you define an area of numbers which can be used for private purposes?

Thanks!

**Comment by xipki** [comment]
Yes. If possible, please add reserved numbers in the following figures:
- Figure 6: C509 Attributes
- Figure 7: C509 Extensions and CSR Attributes
- Figure 8: C509 Certificate Policies
- Figure 9: C509 Policies Qualifiers
- Figure 11: C509 Extended Key Usages

**Comment by emanjon** [comment]
> And since number greater than 65535 requires 8 bytes

In CBOR, I think 65535 requires 3 bytes and number greater than 65535 requires 5 bytes

>So what about to reserve values >= 32678 (0x010000)?
Seems ok to me

**Comment by xipki** [comment]
> In CBOR, I think 65535 requires 3 bytes and number greater than 65535 requires 5 bytes

Yes. Anyway, using value <= 65535 requires less 2 bytes for one private attribute / extension.

**Comment by gselander** [comment]
> If possible, please add reserved values for private use in the following figures:
>
>  Figure 6: C509 Attributes
    Figure 7: C509 Extensions and CSR Attributes
    Figure 8: C509 Certificate Policies
    Figure 9: C509 Policies Qualifiers
    Figure 11: C509 Extended Key Usages

Now values >= 32768 (0x8000) are reserved for private use in those registries, see 982c1be

**Comment by xipki** [comment]
Thanks.
