### ISSUE TITLE
subjectInfoAccess or id-pe-subjectInfoAccess

### ISSUE THREAD

**Issue by emanjon** [cose-wg/CBOR-certificates#148]
The identifiers have no technical purpose. The purpose of having them is for human reader to be able to find information and to easily see that it is the entity they are looking for.

subjectInfoAccess or id-pe-subjectInfoAccess

Both or these exist.
- Could go with most popular
- Could have both
- If only one then id-pe-subjectInfoAccess might be better as a reader can then search for both subjectInfoAccess and id-pe-subjectInfoAccess

**Comment by highlunder** [comment]
Reminder to us: there is a benefit to include the prefixes, such that they can be found by someone searching in the document.

**Comment by highlunder** [comment]
Addressed through merger of PR #151
