### ISSUE TITLE
New structures for C509

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#150]
Hi authors,

do you plan to define following structures?
1. Certificate chain.
2. Private Key + certificate chain.
3. Private Key

In the X.509 environments, it is common to store them as follows:
For 1: PEM or CMS (PKCS#7)
For 2: PEM
For 3: PKCS#8

IMHO, any of PEM, CMS ad PKCS#8 is too complicated for C509.

BR/Lijun

**Comment by emanjon** [comment]
> Certificate chain.

I think we already do
`COSE_C509 = C509Certificate / [ 2* C509Certificate ]`

> Private Key + certificate chain.
> Private Key

Having structure(s) for the private key is a good idea.

**Comment by highlunder** [comment]
(See also ongoing discussions in #136 )

**Comment by emanjon** [comment]
Would something like this be enough? 

```
C509PrivateKey = [
   subjectPrivateKeyAlgorithm: AlgorithmIdentifier,
   subjectPrivateKey: any,
]

C509PEM = [
   C509PrivateKey,
   COSE_C509 / null,
]
```

**Comment by xipki** [comment]
Both C509PrivateKey and C509PEM are OK for me.

**Comment by gselander** [comment]
One option for private key (not optimal) is to use COSE_Key. Private P-256 key:

{
  1:2,   / key type = EC2 /
 -1:1,   / curve = P256 /
 -4: h'D718111F3F9BD91B92FF6877F386BDBFCEA7154268FD7F2FB56EE17D99EA16D4'
         / private key /
}
