### ISSUE TITLE
Location of signature algorithm in C509CertificateRequest

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#167]
In the newest document (https://github.com/cose-wg/CBOR-certificates/blob/master/draft-ietf-cose-cbor-encoded-cert.md), the location of signature algorithm in C509Certificate has been changed as discussed in https://github.com/cose-wg/CBOR-certificates/issues/149).

@authors: What about the same change to C509CertificateRequest?

**Comment by gselander** [comment]
Thanks @xipki!

**Comment by emanjon** [comment]
Unclear to me what "the same change" is in CSR

**Comment by xipki** [comment]
Please refer to https://github.com/cose-wg/CBOR-certificates/pull/170 for more details.

**Comment by emanjon** [comment]
There are no details in #170 except mine.

My understanding is that a DER CSR has a single signature algorithm (correct me if I am wrong). Moving that clearly increases code complexity in some settings. There is no analysis of this. I think such analysis is needed before doing any changes.

**Comment by xipki** [comment]
The idea is to put the signatureAlgorithm field at the beginning of the CertificateRequest so that we can verify the signature by one pass.

**Comment by xipki** [comment]
ASN.1 syntax of X.509 CSR
```
   CertificationRequest ::= SEQUENCE {
        certificationRequestInfo CertificationRequestInfo,
        signatureAlgorithm AlgorithmIdentifier{{ SignatureAlgorithms }},
        signature          BIT STRING
   }

   CertificationRequestInfo ::= SEQUENCE {
        version       INTEGER { v1(0) } (v1,...),
        subject       Name,
        subjectPKInfo SubjectPublicKeyInfo{{ PKInfoAlgorithms }},
        attributes    [0] Attributes{{ CRIAttributes }}
   }
```

While converting X.509 CSR to C.509 CSR, moving the field `signatureAlgorithm`to the beginning may requires to parse the X.509 CSR in two steps. The first step is to read the signatureAlgorithm of X.509 CSR, and the second step to read all other fields of X.509 CSR.

This, however, can be optimized as follows:
1. Read the length, say `t` bytes, of SEQUENCE of `certificationRequestInfo`
2. Skip `t`bytes to reach the position of `signatureAlgorithm`.
3. Move back to the start position of `certificationRequestInfo`, and parsing the remaining fields.
