### ISSUE TITLE
Issuer field in self-signed certificate

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#168]
In the self-signed certificate, the `issuer` field and the `subject` field are identical. Encoding `field` as `NULL` reduces the size of certificate without losing any information.

```
TBSCertificate = (
   ...
   issuer: Name,
   ...,
   subject: Name,
   ...
) 

Name = [ * RelativeDistinguishedName ] / text / bytes
```
may to changed to follows
```
TBSCertificate = (
   ...
   issuer: NullableName,
   ...
   subject: Name,
   ...
) 

Name = [ * RelativeDistinguishedName ] / text / bytes

NullableName = Name / null
```

**Comment by gselander** [comment]
Sounds like a valid case, but I propose to not define a new type. Unless  'null' has a general meaning here, in which case it can be included as a valid value of Name, we could spell out this particular option in the description of the certificate field:

```
   issuer: Name,
   ...
   subject: Name / null,

```

**Comment by xipki** [comment]
@gselander What about 
```
   issuer: Name / null,
   ...
   subject: Name,
```

This is better for the building of certificate chain: issuer.subject = cert.issuer.

**Comment by emanjon** [comment]
```
   issuer: Name / null,
   ...
   subject: Name,
```

Seems good to me

**Comment by emanjon** [comment]
Note that this increases code complexity.
