### ISSUE TITLE
Is a notBefore of null allowed?

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#169]
```
TBSCertificate = (
   ...
   validityNotBefore: Time,
   validityNotAfter: Time,
   ...
)

Time = ~time / null
```
As defined above, a `null`validNotBefore is allowed. But as in the traditional X.509 certificate, validNotBefore shall always be present, and a null vale `999912312355959`does not have any practical application here.

Please either change the syntax definition if `null`is not allowed here, or add text about what the `null`is for.

**Comment by emanjon** [comment]
```
validityNotBefore: ~time,
validityNotAfter: ~time / null,
```

Seems good to me
