### ISSUE TITLE
Typo: AsIdsOrRanges and SignedCerticateTimestamp

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#175]
As in Page 15 (version -09)
```
      AsIdsOrRanges = uint / [uint, uint]
      ASIdentifiers = [ + AsIdsOrRanges ] / null
```
As defined in https://datatracker.ietf.org/doc/html/rfc3779#section-3.2.3, `AsIdsorRanges` shall be renamed to `AsIdorRange`.

And in Page 16, `SignedCerticateTimestamp` shall be `SignedCertificateTimestamp`.

**Comment by highlunder** [comment]
Thank you for spotting this! Now updated in master, closing
