### ISSUE TITLE
Extend the syntax to allow PEN for all OBJECT IDENTIFIER fields.

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#184]
Please extend the syntax of the following cases to allow `pen` besides `~oid`:
    - AlgorithmIdentifier
    - PolicyMappings: .issuerDomainPolicy and .subjectDomainPolicy
    - AccessDescription: .accessMethod
    - PolicyIdentifier
    - PolicyQualifierInfo: . policyQualifierId
    - Attributes: .attributeType
    - Value of the extension id-on-hardwareModuleName
    - Value of the extension id-otherName
    - Value of the extension registeredID

For simplicity, we need to define a new type XXX:

XXX = ~oid / pen

And taking Attribute as example:
```
    Attribute = ( attributeType: int, attributeValue: text ) //
                ( attributeType: ~oid, attributeValue: bytes ) //
                ( attributeType: pen, attributeValue: bytes )
```
is simplified to
```
    Attribute = ( attributeType: int, attributeValue: text ) //
                ( attributeType: XXX, attributeValue: bytes )
```

**Comment by xipki** [comment]
Related to the PolicyMappings, 
```
      PolicyMappings = [
        + (issuerDomainPolicy: ~oid, subjectDomainPolicy: ~oid)
      ]
```

The `issuerDomainPolicy`and `subjectDomainPolicy` need also to be extended to allow the `uint`type, as follows:
```
      PolicyMappings = [
        + (issuerDomainPolicy: uint/~oid/pen, subjectDomainPolicy: uint/~oid/pen)
      ]
```

**Comment by xipki** [comment]
Changes submitted under https://github.com/xipki/CBOR-certificates/commit/89109f296a9ee3cfbfbe6a5757f69f7f107ac2fb, and is ready to PR.

**Comment by gselander** [comment]
Since we removed the 'pen' case, we close this issue.
