### ISSUE TITLE
Encoding of IPAddress

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#185]
Page 15 (draft -09): 
```
Address = bytes / uint
```

And under https://datatracker.ietf.org/doc/html/rfc3779#section-2.2.3
```
IPAddress           ::= BIT STRING
```
Does encoding in CBOR require IPAddress has unusedbits `0`? If not, how to encode the unusedbits?

**Comment by highlunder** [comment]
Please check if you/someone can provide an example / a sample

**Comment by gselander** [comment]
Closing since it is a subset of #187
