### ISSUE TITLE
Attribute domainComponent ( 0.9.2342.19200300.100.1.25)

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#191]
Please extend the following text in Page 7 (in draft -09) 
```
The Attribute Email Address is always an IA5String.
```
to
```
The Attributes Email Address and domainComponent are always an IA5String.
```

The reason is a DomainComponent allows only IA5String, as specified in RFC 3039 (https://datatracker.ietf.org/doc/html/rfc3039.html#appendix-A.1):
```
domainComponent             AttributeType ::=
                            { 0 9 2342 19200300 100 1 25 }
DomainComponent ::=         IA5String
```

**Comment by highlunder** [comment]
Looks good, @xipki is welcome to propose a PR!

**Comment by gselander** [comment]
Add text "Note that domainComponent in [RFC 3039] is IA5String."

**Comment by highlunder** [comment]
Added the content of PR #207 directly to master to avoid conflicts, closing!
