### ISSUE TITLE
Simplify the CDDL of Name

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#195]
In draft -09, name allows `RelativeDistinguishedName`with more than one `Attribute`. In the practice, it is rare to have such cases. If we exclude such cases, the CDDL of `Name` can be simplified:

From
```
    Name = [ * RelativeDistinguishedName ] / text / bytes

    RelativeDistinguishedName = Attribute / [ 2* Attribute ]
``` 
to
```
    Name = [ * Attribute ] / text / bytes
``` 

 This simplifies also the implmentation, especially in the native C509. As defined in current CDDL, we need
`Attribute[][]` to present a Name, while in the simplified CDDL, only Attribute`[]` is enough.

**Comment by highlunder** [comment]
We agree we think it is rarely used, but we need to ask the mailing list(s) if they know more about the relevance:
@xipki to do a PR with the proposed change
@gselander to mail at least COSE to ask for approval/dis-a.

**Comment by highlunder** [comment]
Merged suggestion BUT keeping issue open, if the COSE WG comes back and wants the previous version restored

**Comment by gselander** [comment]
Closing this, no comment from the WG.
