### ISSUE TITLE
Deterministic Encoding of an Attribute

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#198]
In draft -09, an Attribute is encoded as follows
```
    Attribute = ( attributeType: int, attributeValue: text ) //
                ( attributeType: ~oid/pen, attributeValue: bytes )
```

1. It is not clear how to encode the attribute, if it has the assigned `int` type, and
   - For emailAddress and domainComponent: the attribute value is not `IA5String` encoded,
   - For other attributes, the value is neither `PRINTABLE STRING` nor `UTF8 STRING` encoded.
2. Shall the attribte type be negative (for `PRINTABLE STRING`) or posive (for `UTF8 STRING`), if the attribute type is of fixed string type, but not one of `PRINTABLE STRING` and `UTF8 STRING`, e.g. the emailAddress and domainComponent?

**Comment by highlunder** [comment]
1. We need to clarify the text to remove the ambiguity, that we don't support
2. Adapt the proposal given

**Comment by highlunder** [comment]
Accepting and merging PR with clarifying text!
