### ISSUE TITLE
Error in "Example Encoding of Extensions"

### ISSUE THREAD

**Issue by aidenYang97** [cose-wg/CBOR-certificates#203]
In the C509 Extended Key Usages Registry, the value for id-kp-OCSPSigning is listed as 9. However, in the third example provided in the section 3.3.1, the CBOR array is shown as [3, 6]. Based on the correct value for id-kp-OCSPSigning, the CBOR array should be [3, 9].

**Comment by gselander** [comment]
Thanks @aidenYang97, fixed in 2c8b09d.
