### ISSUE TITLE
Remove the support of PEN

### ISSUE THREAD

**Issue by xipki** [cose-wg/CBOR-certificates#204]
Encoding an object identifier as PEN saves only 2 bytes compared to ~oid, this however results in more complex process e.g. serialization, deserialization, comparing, etc. And as discussed in the comments of https://github.com/cose-wg/CBOR-certificates/issues/197, we suggest to remove the PEN.

**Comment by highlunder** [comment]
Well in line with the conclusion with our joint discussions - merged, and closing!
