### ISSUE TITLE
Add id-Wei25519  and id-Wei448

### ISSUE THREAD

**Issue by emanjon** [cose-wg/CBOR-certificates#50]
a.  id-Wei25519 OBJECT IDENTIFIER ::= TBD (Requested value: {iso(1)
       identified-organization(3) thawte (101) 108 });

   b.  id-Wei448 OBJECT IDENTIFIER ::= TBD (Requested value: {iso(1)
       identified-organization(3) thawte (101) 109 }).

**Comment by highlunder** [comment]
Question to @emanjon , did you already request these IDs from IANA, or are you saying they should be requested?

(Possibly of relevance for future work: https://datatracker.ietf.org/doc/html/draft-ietf-lwig-curve-representations-23)

**Comment by highlunder** [comment]
This, or the NIST version might be added later if/when it becomes relevant!
