### ISSUE TITLE
Decide which optimizations are worth having

### ISSUE THREAD

**Issue by emanjon** [cose-wg/CBOR-certificates#56]
- I removed the optimization to skip the outer array in subject and issuer.

- "If subjectAltName contains exactly one dNSName, the array and the int are omitted and extensionValue is the dNSName encoded as a CBOR text string." This saves 2 byte

- The EUI-64 optimization saves 17 bytes and should definitly be kept.

- The optimization for keyusage saves 2 bytes.

- The optimization for the special case utf8string common name saves 3 bytes.

**Comment by highlunder** [comment]
I'd vote to ditch the subjectAltName optimization (and the first which you already removed) and keep the rest.

**Comment by highlunder** [comment]
Conclusion for now is to keep the remaining optimizations.
