### ISSUE TITLE
Big numbers for RSA+SHA-1

### ISSUE THREAD

**Issue by emanjon** [cose-wg/CBOR-certificates#64]
1,2,3,5,9 byte assignement for RSA+SHA-1?

I currently has a 1 byte assignement
mcr has suggested a 5 byte asignment
In general there is quite many 2 byte asignments (512)

**Comment by highlunder** [comment]
Is this referring to "RSASSA-PKCS1-v1_5 with SHA-1", with val -256 in the [11.9] C509 Signature Algorithms Registry?

If so, it has a clear "don't use" comment, as do everything with SHA-1. So do we need to spend time accommodating for those hopefully more and more rare cases?

**Comment by highlunder** [comment]
Current 2-byte version is deemed ok!
