### ISSUE TITLE
CRL and OCSP? The same CBOR encoding could trivially be used for CRL and OCSP as well.

### ISSUE THREAD

**Issue by emanjon** [cose-wg/CBOR-certificates#68]

**Comment by emanjon** [comment]
OCSP?

**Comment by emanjon** [comment]
For OCSP there would be a need to discribe the details on how OSCP stapling is transfered in TLS. COSE/EDHOC does currently not support OCSP stapling.

**Comment by highlunder** [comment]
Closing for now, the revocation management issues have been moved to draft-cose-cbor-revocation-management. (We might keep the same issue-tracker also for that document, to be decided.)
