### ISSUE TITLE
Support subset of extentions

### ISSUE THREAD

**Issue by emanjon** [cose-wg/CBOR-certificates#71]
Seems like only a subset of extensions are actively used. COSE should discuss which parts do not need to be supported.

AuthotityKeyIdentifier seems to only contain KeyIdentifier.

CDDL: KeyIdentifier

CRLDistributionPoints seems only contain DistributionPoint of type Generalnames of type DNSname.

CDDL: [ GeneralNames ]

...

**Comment by highlunder** [comment]
Both of these seem to be already updated/expanded in current -04 version, section 3.3 Encoding of Extensions. Ready to close as resolved?

**Comment by highlunder** [comment]
Resolved!
