### ISSUE TITLE
CBOR Sequence parsing in libraries

### ISSUE THREAD

**Issue by emanjon** [cose-wg/CBOR-certificates#76]
Do the format need to be adjusted to make implementation with some CBOR encoders and decoders easier?

Laruance Lundblade: Some CBOR decoders don’t allow access a sub-part of the encoded CBOR so it can be input into the signature algorithm. Suggest to wrap TBSCertificate in a byte string

Stefan Hristozov : Easy to calculate offset with tinycbor and his own Rust implementation

Joel Höglund: Small on the wire size is important.

Carsten Bormann: One valid use of CBOR is to prefix a single CBOR data item to a byte sequence (not itself packaged as a CBOR string). 

Wrapping TBSCertificate in a byte string would add 2-3 additional bytes.

**Comment by emanjon** [comment]
Discussion at interim 2020-12-16 was that this is a tradeoff without a clear answer. Should be evaluated at a later point.

**Comment by highlunder** [comment]
Currently no consensus, closing! (Can be reopened if there are new input.)
