### ISSUE TITLE
Certificate Signing Request (CSR)

### ISSUE THREAD

**Issue by StefanHri** [cose-wg/CBOR-certificates#77]
Does it make sense to have CBOR encoded CSRs? For example, if we have a constrained IoT device communicating over a constrained network the device may want to get a certificate from a remote CA by sending a CSR. What needs to be contained in the CSR and how should it be encoded?

**Comment by gselander** [comment]
How about this:
https://tools.ietf.org/id/draft-selander-ace-coap-est-oscore-04.html#name-enrollment-re-enrollment-of

One example showing how EDHOC could be used with CBOR encoded CSR is shown in slide 3 of
https://datatracker.ietf.org/meeting/109/materials/slides-109-ace-draft-selander-ace-ake-authz-01.pdf

**Comment by StefanHri** [comment]
This is exactly what I am looking for. I think it will be good to have a short section in this document about CSR encoding and a CSR test vector.

**Comment by StefanHri** [comment]
[1] says: 
The essential information fields for the CA to verify are the following:
* Information about the subject, here condensed to the subject common name,
* subject public key, and
* signature made by the subject private key.

However, according to [2] a certificate signature is calculated over the following fields:
* cborCertificateType,
* certificateSerialNumber,
* issuer,
* validityNotBefore,
* validityNotAfter,
* subject (subject common name),
* subjectPublicKeyAlgorithm,
* subjectPublicKey,
* extensions,
* issuerSignatureAlgorithm,

Is it not necessary to include in the CSR also: 
* cborCertificateType,
* validityNotBefore,
* validityNotAfter,
* subjectPublicKeyAlgorithm,
* extensions,
If those fields are not included in the CSR, how the CA can know them? Or those fields are negotiated out of band?

In this way the CSR will contain all fields of TBSCertificate except:
* certificateSerialNumber,
* issuer,
* issuerSignatureAlgorithm,
which are known to the CA? 

[1]: https://tools.ietf.org/id/draft-selander-ace-coap-est-oscore-04.html#name-enrollment-re-enrollment-of
[2]: https://datatracker.ietf.org/doc/html/draft-mattsson-cose-cbor-cert-compress-05#section-3.1

**Comment by highlunder** [comment]
I think the common case is that the CA is the entity deciding the values for validity and extensions. But I agree that the info on the subjectPublicKeyAlgorithm must be communicated somehow.

//Joel
________________________________
Från: Stefan <notifications@github.com>
Skickat: den 26 december 2020 21:44
Till: EricssonResearch/CBOR-certificates <CBOR-certificates@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: Re: [EricssonResearch/CBOR-certificates] Certificate Signing Request (CSR) (#77)


1<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftools.ietf.org%2Fid%2Fdraft-selander-ace-coap-est-oscore-04.html%23name-enrollment-re-enrollment-of&data=04%7C01%7Cjoel.hoglund%40ri.se%7C01c87289a4e6441c505b08d8a9df1cfd%7C5a9809cf0bcb413a838a09ecc40cc9e8%7C0%7C0%7C637446123480913859%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hs%2FuX%2FuR%2FFPP09eB%2Bg67tGcjYnx93AYKs7U%2FUh8acaM%3D&reserved=0> says:
The essential information fields for the CA to verify are the following:

  *   Information about the subject, here condensed to the subject common name,
  *   subject public key, and
  *   signature made by the subject private key.

However, according to 2<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdatatracker.ietf.org%2Fdoc%2Fhtml%2Fdraft-mattsson-cose-cbor-cert-compress-05%23section-3.1&data=04%7C01%7Cjoel.hoglund%40ri.se%7C01c87289a4e6441c505b08d8a9df1cfd%7C5a9809cf0bcb413a838a09ecc40cc9e8%7C0%7C0%7C637446123480923853%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jFq4723DfSiVTiaq%2FI%2Fg8n88uHnoJzZpokEckUvfCAM%3D&reserved=0> a certificate signature is calculated over the following fields:

  *   cborCertificateType,
  *   certificateSerialNumber,
  *   issuer,
  *   validityNotBefore,
  *   validityNotAfter,
  *   subject (subject common name),
  *   subjectPublicKeyAlgorithm,
  *   subjectPublicKey,
  *   extensions,
  *   issuerSignatureAlgorithm,

Is it not necessary to include in the CSR also:

  *   cborCertificateType,
  *   validityNotBefore,
  *   validityNotAfter,
  *   subjectPublicKeyAlgorithm,
  *   extensions,
If those fields are not included in the CSR, how the CA can know them? Or those fields are negotiated out of band?

In this way the CSR will contain all fields of TBSCertificate except:

  *   certificateSerialNumber,
  *   issuer,
  *   issuerSignatureAlgorithm,
which are known to the CA?

**Comment by mcr** [comment]
Is this the right ticket to talk about Stapled OCSP responses as well?

**Comment by gselander** [comment]
@mcr Depends. If "CBOR encoded revocation info" please use #68.

**Comment by emanjon** [comment]
I quickly made CDDL for CSR based on the C509 draft

```
C509CertificationRequest = [
   TBSCertificationRequest,
   subjectPoPValue: any,
]

; The elements of the following group are to be used in a CBOR Sequence:
TBSCertificationRequest = (
   c509CertificationRequestType: int,
   subject: Name,
   subjectPublicKeyAlgorithm: AlgorithmIdentifier,
   subjectPublicKey: any,
   attributes: [ * Attribute ],
   subjectPoPAlgorithm: AlgorithmIdentifier,
)

Attribute = ( attributeType: int, attributeValue: any )
```
I think there is agreement to add this, so I will make a commit with a new section so that we have something to work from.

The format above rfc2986. Most definitions can just be reused from draft-ietf-cose-cbor-encoded-cert

- I don't think there is any reason to have a CBOR CSR with signature over DER like we have done with C509 certificates. But having a type int is likely good anyway.
-  the rfc2986 name signaturealgorithm does not match the algorrithms in RFC 6955. I change the name PoP following 6955. Signature algorithms is now a special case.
- The RFC 6955 algorithm would need to get int code points in the draft..
-  rfc2986 does not sign the signature, but there seems to be no reason to not do this, so I made the format follow C509.
- I don't know which attributes would have to registered or if attributes are used.

**Comment by emanjon** [comment]
Updated version

The section defines the C509 Certificate Signing Request (CSR) format based on and compatible with RFC 2986 {{RFC2986}} reusing the formatting for C509 certificates defined in {{certificate}}. There are currently two c509CertificateSigningRequestType values defined, c509CertificateSigningRequestType = 0 requests a c509CertificateType = 0 and c509CertificateSigningRequestType = 1 requests a c509CertificateType = 1 . subjectProofOfPossessionAlgorithm can be a C509 signature algorithm or a non-signature Proof-of-Possession Algorithm as defined in e.g. RFC 6955. CSR attributes other than extensionRequest are not supported.

C509CertificateSigningRequest = [
   TBSCertificateSigningRequest,
   subjectProofOfPossessionValue: any,
]

; The elements of the following group are to be used in a CBOR Sequence:
TBSCertificateSigningRequest = (
   c509CertificateSigningRequestType: int,
   subject: Name,
   subjectPublicKeyAlgorithm: AlgorithmIdentifier,
   subjectPublicKey: any,
   extensionsRequest : Extensions,
   subjectProofOfPossessionAlgorithm: AlgorithmIdentifier,
)

{: #fig-CBORCertCDDL title="CDDL for C509CertificateSigningRequest."} {: artwork-align="center"}

After verifying the subjectProofOfPossessionValue, the CA MAY transform the C509CertificateSigningRequest into a RFC 2985 CertificationRequestInfo for compatibility with existing procedures and code.

**Comment by emanjon** [comment]
I mentioned use case is that the CA decides which extentions to put in. The CSR format would then have to differentiate between asking for no extentions and to let the CA decide.

**Comment by emanjon** [comment]
Unclear if any CSR attributes other than extensionsRequest need to be supported. Should the CSR format allow for future attributes or should that be left for a future 509CertificateSigningRequestType

**Comment by mcr** [comment]
John Mattsson ***@***.***> wrote:
    > - I don't think there is any reason to have a CBOR CSR with signature
    > over DER like we have done with C509 certificates.

are we compressing or replacing?
If we are replacing, then we could stray much further.

-- 
]               Never tell me the odds!                 | ipv6 mesh networks [ 
]   Michael Richardson, Sandelman Software Works        | network architect  [ 
]     ***@***.***  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by emanjon** [comment]
Here is a list of varous alternatives:
----------------------------------------------

Subject creates

1) C509 CSR
2) PKCS #10 CSR
2) PKCS #10 CSR and compress it to C509 CSR


Issuer processes

a) C509 CSR 
b) PKCS #10
c) C509 CSR uncompressed to a PKCS #10 CSR
d) C509 CSR uncompressed to a PKCS #10 CertificationRequestInfo

Issuer delivers

α) C509 certificate of type 0
β) C509 certificate of type 1 (i.e X.509 compressed to C509)
γ) X.509

------------------------------------------------------------------

The current suggestion in the draft address the following four compbinations.

1) + a) + α)
1) + d) + α)

1) + a) + β)
1) + d) + β)

I did not think compression is as important for CSR as for the actual certificates. 
I think c) or d) is important to make it easy to add support in an existing CA.

Comments on what should be supported is very welcome.

**Comment by gselander** [comment]
What is requested and the format of the request can also be expressed with headers / options "Accept" and "Content-Format", see 
https://github.com/ace-wg/est-oscore/issues/35

Maybe we should settle for just describing the format of the current CSR, i.e. c509CertificateRequestType with formats 1) and 3) above, analogous to c509CertificateType.

**Comment by highlunder** [comment]
Converging on allowing only the two following cases:

c509CertificateRequestType: 1 => use both compressed CSR and X509
c509CertificateRequestType: 0 => use both native cbor-CSR and C509

**Comment by highlunder** [comment]
*update* / Carsten's proposal
c509CertificateRequestType: 3 => use both compressed CSR and X509
c509CertificateRequestType: 0 => use both native cbor-CSR and C509

**Comment by gselander** [comment]
Following the discussion at IETF 118 I made a proposal directly on the master, please review.

**Comment by gselander** [comment]
Another update in  10b66e43c1f4eb8a89ebd775965a26e03207d01b

**Comment by emanjon** [comment]
Agree that this should be closed. Let's open new more specific issues if needed.
