### ISSUE TITLE
Eventually an error in the text vector

### ISSUE THREAD

**Issue by StefanHri** [cose-wg/CBOR-certificates#79]
In section A.1.1 the public key is encoded as:
```
58 21 02 B1 21 6A B9 6E 5B 3B 33 40 F5 BD F0 2E 69 3F 16 21 3A 04 52 5E D4 44 50 B1 01 9C 2D FD 38 38 AB
```

The second byte (0x21) indicates the length of the byte string. The length is 32 byte which is in hex 0x20 not 0x21?

**Comment by highlunder** [comment]
The key-length of the compressed key includes the "02" + the original 32 bytes, which makes the resulting full key length 33 bytes.

If you have suggestions for how to present this in a more self explainatory way we are happy to try to clarify!

**Comment by highlunder** [comment]
Small internal ref. added. I keep this issue open if others want to have a say about the wording.

**Comment by highlunder** [comment]
Phrasing accepted
