### ISSUE TITLE
File format for saving CBOR certificates and CSRs

### ISSUE THREAD

**Issue by StefanHri** [cose-wg/CBOR-certificates#81]
What is the recommended file format for saving CBOR certificates and CSRs? 
Is it .der?

**Comment by mcr** [comment]
Hi, I think that we should have a MIME TYPE for them. Within that, we would want to define an extension.  Maybe ".ccert"
or ".ccrt".

There is a tussle between having a 4-8-byte magic number at the beginning of the certificate, vs having a really short CBOR tag for transmission.  I suggest we not compromise, but do both.  I had this problem this week, and I want to propose that the 
file format for a .ccert is actually:

CBOR-Sequence [
   Tag<u64-magic-number>
   Encoded-Certificate...
]

Note that we have in the PEM vs DER certificate world, a problem: ".pem" files evolved to support having multiple certificates in them.  (and even having a private key and then series of certificates), but the DER encoded equivalents do not support that.
So, let's EXPLICITELY support CBOR-Sequence of certificates, and let's allow that the first item might be just a tag.

I will write a document for CBOR WG, on allocating this /etc/magic, file(1) friendly tag.

**Comment by mcr** [comment]
We now have draft-ietf-cbor-file-magic, which makes a concrete BCP on this.

**Comment by emanjon** [comment]
Waiting for @gselander to specify content formats

From RFC 9277:
  

>    For CBOR data items that form a
>    representation that is already described by such a Content-Format
>    Number, a tag number has proactively been allocated in Section 4.3
>    (see Appendix B for details and examples).

**Comment by gselander** [comment]
Fixed with #157
