### ISSUE TITLE
Certificate chain optimizations

### ISSUE THREAD

**Issue by emanjon** [cose-wg/CBOR-certificates#82]
In self-issued certficates as well as when cbor certificates are used in chains/bags like the TLS certificate message or COSE c5chain, c5bag there is a lot of duplicated informatation. 

The issuer field is almost always the same as a subject field in the same or another certificate.
The authority key identifier key identifier is almost always the same as a subject key identifier in the same or another certificate.
The authority key identifier  authority Cert Issuer is almost always the same as subject field in the same or another certificate.

CBOR certificates could provide optimizations for self-issues certificates (they are send on the wire quite often in TLS, e.g. tools.ietf.org) as well as for certs that are sent in an certificate chain.

The issuer and key identifier in these cases could just be a relative pointer to the certificate with the information. I.e. typically 0 or 1.

For the example tools.ietf.org certificate the saving are quite large. 1075 bytes instead of 1242 bytes and for self-issued certs with a larger authority key information the saving are even bigger.

Should CBOR certificates provide optizations for self-issued certificates. I.e. issuer and auth key id is replaced with 0?
Should CBOR certificates provide optizations for certs in chains . I.e. issuer and auth key id is replaced with 1?

+ Provides large savings.
- Added coplexity, Makes CBOR compression two pass 
- May not be needed for TLS with Brotli as Brotli hopefully compresses these things anyway (should be tested)

**Comment by highlunder** [comment]
Brotli support can be supported by new COSE header format(s)

**Comment by highlunder** [comment]
Agreement to leave as is!
