### ISSUE TITLE
Implications of CBOR cert being a CBOR sequence not a data item

### ISSUE THREAD

**Issue by laurencelundblade** [cose-wg/CBOR-certificates#83]
A CBOR sequence can’t be an item in a CBOR array or the value of a CBOR map entry. The only way to use a CBOR sequence in a CBOR protocol is to wrap it in a byte string. That means whenever a CBOR Certificate is used in another CBOR protocol is must be wrapped in a byte string.

This is in contrast to many other CBOR protocols that are not CBOR sequences and thus don’t need the byte string wrapping when incorporated into another CBOR protocol. CBOR Cert seems unusual in its design choice.

The c5chain and c5bag COSE headers are the incorporation of CBOR Cert into the COSE protocol. The way they are defined now, there is byte string wrapping inherited from the x5bag and x5chain header parameters, so it does work.

It seems very easy and inexpensive to make CBOR Cert like the other protocols by just making it into a CBOR array. It would add one byte to the start of the cert.

**Comment by emanjon** [comment]
I think wrapping in an array is the way to go. The COSE header parameters for C509 are now defined as doule arrays

COSE_C5 = [ [ + C509Certificate ] ]

Could be that the the inner [] should be included in C509Certificate, but this would add a byte for non-CBOR protocols like TLS. I don't the array help there. So maybe the current definition is the best.

**Comment by laurencelundblade** [comment]
This is what is in the draft now, I'm I'm pretty sure it is incorrect CDDL:

`  COSE_C5 = [ + CBORCertificate ]`

The problem is that CBORCertificate is a group, not an array or a sequence-wrapping byte string. There's no structure to tell the end of one certificate from the start of the next in COSE_C5.

My preferred solution would be to make CBORCertificate an array instead of a sequence. It will add one byte for all uses of compressed certs, but it will reduce complexity a lot by making it like a more normal CBOR protocol. People will keep making mistakes like the one right now in COSE_C5 unless we make it an array. If we can't even get it right, think of what will happen for others.

So I prefer this fix:
```
CBORCertificate = [
   TBSCertificate,
   issuerSignatureValue : any,
]
```

With this the above COSE_C5 works correctly.

If CBORCertificate is left as a sequence because you really really want to save that one byte, then COSE_C5 can be fixed with arrays like this:
`  COSE_C5 = [ + [CBORCertificate]]`
or with byte-string wrapping like this:
`  COSE_C5 = [ + bstr .cborseq CBORCertificate ]`

If CBORCertificate is kept as a sequence, then one of the above two solutions will have to be used **every** time a CBORCertificate is put into another CBOR protocol. You only save the one byte in non-CBOR protocols like TLS!

**Comment by emanjon** [comment]
>This is what is in the draft now, I'm I'm pretty sure it is incorrect CDDL:
>
>COSE_C5 = [ + CBORCertificate ]

I don't know why you think this was incorrect CDDL.

RFC 8610 has the following example

[+(left: uint, right: uint)]

Also, this is not in the current version. It has already been changes in the GitHub version based on the discussions during the interim

**Comment by highlunder** [comment]
Updated / fixed in current 04 draft, using the proposed array wrapping:
C509Certificate = [
       TBSCertificate,
       issuerSignatureValue : any,
 ]
- Closing
