### ISSUE TITLE
Should a tag be defined?

### ISSUE THREAD

**Issue by laurencelundblade** [cose-wg/CBOR-certificates#84]
It is common to define a tag for CBOR messages. For example COSE and CWT have tags. Should a tag be defined? 

I don't think you can tag a sequence, so it would have to be an array. See #83

**Comment by emanjon** [comment]
Make sense to define a tag for a CBOR certificate. 

https://tools.ietf.org/html/draft-bormann-cbor-notable-tags-02 defines

   *  Tag 63, registered by this document, is a parallel to tag 24, with
      the single difference that its byte string tag content carries a
      CBOR Sequence [RFC8742] instead of a single CBOR data items.

But if I understand correctly that is a sequence embedded in a bstr embedded in a tag.

Defining a tag-array-seq would make sense

**Comment by mcr** [comment]
self-assigning to @mcr

**Comment by emanjon** [comment]
I think the tag definition is done, not comment on this lately.
