### ISSUE TITLE
Title includes "certificates"

### ISSUE THREAD

**Issue by emanjon** [cose-wg/CBOR-certificates#88]
This is no longer correct if we include CSR (or CRL, OSCP, ....)

**Comment by gselander** [comment]
Other proposals are welcome, but certificates will still the main content. I think it is better to have a short title brandning the key component than a long all-inclusive title.

**Comment by highlunder** [comment]
I agree with Göran

**Comment by emanjon** [comment]
No chenge, lets change abstrct later
