### ISSUE TITLE
SW-Implementation of CBOR-certificates

### ISSUE THREAD

**Issue by armandomiguel** [cose-wg/CBOR-certificates#93]
Hello everyone,

Is there any known software implementation for generating, validating and managing CBOR certificates, as well as converting X.509 certificates into the CBOR format?

My colleague Stefan (@StefanHri) and I work as research associates at Fraunhofer AISEC and are interested in implementing such functions in the form of a command-line tool and eventually as an expansion to our [uedhoc-uoscore](https://github.com/Fraunhofer-AISEC/uoscore-uedhoc) implementation, which is lead by Stefan. 
Before starting with this implementation, we would like to know if there is an existing implementation or at least one in progress.

**Comment by emanjon** [comment]
I have a almost complete implementation of a X.509 to C509 command-line tool written in RUST. Maybe we can setup a meeting and discuss.

**Comment by highlunder** [comment]
At RISE we have mainly done prototype implementations (in C) of subsets of the functionality, of limited reuse value. But if you decide to discuss with John/Ericsson, we would be interested in joining.

**Comment by StefanHri** [comment]
I have two tools - one very simple in C and one more fancy in Rust. Both can produce only native C509. @emanjon: I don't know if it is possible and if it makes sense but eventually it will be cool if we can merge our Rust implementations.

Additionally, our EDHOC implementation has currently a native C509 parser.

**Comment by emanjon** [comment]
I will release my RUST implementation of X.509 to C509 next week. The code is now almost complete. I will just verify that it aligns with draft-ietf-cose-cbor-encoded-cert-00 or document where it falls short.

**Comment by StefanHri** [comment]
Hi,
I put my CBORcert command-line tool on git hub https://github.com/StefanHri/cborcert. Feedback and contributions are welcome. You can create a sample PKI by calling the script  `sample_pki.sh` and examine all created keys, CSRs, and certificates. 

Regarding CSRs:
I am generating CSRs as a CBOR sequence: 

```
CSR = (
    cbor_cert_type
    subject_common_name
    iana_pk_alg_ID
    pk
    signature
)
```
As discussed this is a suggestion and we can change it if something more is required in the CSR or something can be dropped.

**Comment by emanjon** [comment]
Thanks for the suggestion Stefan. I think the standardized format needs to be a bit more general than the suggestion above and the suggestion in the ACE draft. I made a commit of a general formal using all the existing definitions from C509 certificates. I think the CSR can be made general while still being very small for constrained IoT.

We have not calculated any sized yet, but we will do so until IETF 111.

**Comment by derekatkins** [comment]
@StefanHri  --
> I have two tools - one very simple in C and one more fancy in Rust. Both can produce only native C509. @emanjon: I don't know if it is possible and if it makes sense but eventually it will be cool if we can merge our Rust implementations.

How workable is the C implementation?  Is it something you might be willing to share?

**Comment by StefanHri** [comment]
The C tool was very experimental and it is already quite outdated. But you can take a look at the rust one https://github.com/StefanHri/cborcert

**Comment by derekatkins** [comment]
> The C tool was very experimental and it is already quite outdated. But you can take a look at the rust one https://github.com/StefanHri/cborcert

Thanks.  Unfortunately I need a C implementation and would rather build on someone else's instead of writing it from scratch.  (I also need one in Java).

**Comment by manishamalik53** [comment]
Hi @derekatkins ,

Did you implement the CBOR certificates in C? Are you willing to share the same?

**Comment by armandomiguel** [comment]
Hello @manishamalik53,

We at Fraunhofer AISEC are finishing an implementation of CBOR certificates in C (some of the partially supported extensions are still to be added).
I will comment on this thread as soon as the implementation is ready to be shared.

**Comment by gselander** [comment]
Great news Armando!

**Comment by derekatkins** [comment]
@manishamalik53 -- Hi.  We did create an implementation (on top of libcbor), but I would definitely not call it a generic implementation.  It is very specific to our use-case, and was not written as a standalone library.  I do not feel it is currently in a state where it could be shared and reused, but I will see if that can happen eventually.

**Comment by highlunder** [comment]
To highlight the partial progress and ongoing work, we have opened #163 and close this old issue.
