### ISSUE TITLE
Describe CA processing

### ISSUE THREAD

**Issue by emanjon** [cose-wg/CBOR-certificates#96]
The property that C509 can be deployed as a small shim layer at existing CAs should be given more space and be explained better. I that is one of the big motivations and advantages with C509. An existing CA can continue to use their existing procedures and code for PKCS#10 and DER encoded X.509 and only implement C509 as a layer on top of that.

When receiving a C509 CSR, the CA transforms it into a DER encoded RFC 2986 CertificationRequestInfo and use that with existing processes and code to produce an RFC 5280 DER encoded X509 certificate. The DER encoded X509 is then transformed into a C509 certificate.

**Comment by highlunder** [comment]
Solved through PR#134
