### ISSUE TITLE
Compression of extentions, certificates, or chains.

### ISSUE THREAD

**Issue by emanjon** [cose-wg/CBOR-certificates#98]
The TLS size examples in the -01 draft shows that even after C509 encoding, Brotli can still compress a cetificate chain quite much.

Test on RPKI certs should that Brotli can compress individual extensions or certs quite much, even after CBOR encoding.

I think we should discuss if Brotli (or some other general compression mechanism should be used in COSE. Likely after the signature has been calculated, i.e. not in individual extensions.

- C509 could specify a compressed cert type which take a C509 cert and produce a compressed C509.
- COSE_C509 could specify a compressed chain cert type which take a COSE_C509 cert and produce a compressed COSE_C509.

There has also been discussion on using CBOR packed, but there has to my knowledge not been any tests being done. https://datatracker.ietf.org/doc/html/draft-ietf-cbor-packed-02

**Comment by emanjon** [comment]
I think we should define COSE_C509 as something like 

COSE_C509 = [ comp : int, C509Certificate / [ 2* C509Certificate ] / bytes]

where comp = 0 is no compression and other values of comp are use for a compressed chain conveyed in a bstr. This provides significant further compression when applied to example HTTPS certificate chains. The numbers below are from TLS but would be approximate for COSE_C509 as well.

+-------------------+------+---------------+
|                   | C509 | C509 + Brotli |
+-------------------+------+---------------+
| ECDSA HTTPS Chain | 1409 |          1058 |
+-------------------+------+---------------+
| RSA HTTPS Chain   | 3957 |          2841 |
+-------------------+------+---------------+

**Comment by highlunder** [comment]
Agreement to not address here as part of C509
